spring:
  application:
    name: zipkin
server:
  port=8087
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
logging:
  level:
    org:
      springframework:
        web: debug
